### ISSUE TITLE
Bug: can't use address in querystring

### ISSUE THREAD

**Issue by SilVdB** [DataBrokerDAO/databrokerdao-dapi#26]
How to reproduce:

try to query the streamregistry/list with purchaser=[address of the purchaser], no items are returned, even when the address is correct.

**Comment by RutgerBevers** [comment]
Isn't this in /purchaseregistry/list ?
However streamregistry/list also seems broken: cannot filter on owner

**Comment by RutgerBevers** [comment]
Fixed by adding ~ before the address (Like param=~0x3df2fd51cf19c0d8d1861d6ebc6457a1b0c7496f)

**Comment by SilVdB** [comment]
God bless Hilke :)
