### ISSUE TITLE
Purchases tab does not work.

### ISSUE THREAD

**Issue by roderik** [DataBrokerDAO/databrokerdao-dapi#43]
Bought a stream and a set on with account 0xf68bc54b6c6f0c63afd0ebb2dbe2eeba8ad0fa52 on [staging](https://dapp-staging.databrokerdao.com/purchases) but no purchases appear, even after a 10 minute wait.

**Comment by SilVdB** [comment]
I have not encountered it myself since we did some serious bughunting a few months ago, but it seems like it still happens sometimes. I suspect a bug in lib-ethereum sync
